### PR TITLE
[PATCH] Fixed the issue with multiple simultaneous users

### PR DESCRIPTION
**Pull request by Diapolo10**
Long story short, I fixed the problem with race conditions causing problems when multiple users are attempting to upload/download files. I also swapped `requirements.txt` for a Poetry-based solution, but you can ignore that if you want - it just made my debugging experience smoother.

There was also something weird going on with README saying the project had an MIT license, but the license file itself claimed otherwise. I opted to err on caution and updated the README to reflect how the license file talks about GNU GPLv3 instead.

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Thanks a lot for your valuable contribution 🥇 💯  @Diapolo10

**Comment by Diapolo10** [comment]
> Thanks a lot for your valuable contribution 🥇 💯 @Diapolo10

Just in case, have you verified on your end that this fix actually works?

**Comment by pooranjoyb** [comment]
> > Thanks a lot for your valuable contribution 🥇 💯 @Diapolo10
> 
> Just in case, have you verified on your end that this fix actually works?

Yes, it works! 💯

**Comment by Diapolo10** [comment]
> > > Thanks a lot for your valuable contribution 🥇 💯 @Diapolo10
> > 
> > 
> > Just in case, have you verified on your end that this fix actually works?
> 
> Yes, it works! 💯

Glad to hear!

**Pull request merged**
